### ISSUE TITLE
使用时发生闪退

### ISSUE THREAD

**Issue by ma125125t** [alibaba/Lokie#1]
```
Class cls = NSClassFromString(@"ViewController");
    [cls Lokie_hookMemberSelector:@"viewDidAppear:" withBlock:^(id target, BOOL ani){
           NSLog(@"LOKIE: viewDidAppear 调用之前会执行这部分代码");
    }policy:LokieHookPolicyBefore];
```

Thread 1: Exception: "+[ViewController Lokie_hookMemberSelector:withBlock:policy:]: unrecognized selector sent to class 0x10f1f43b0"

环境：
模拟器iPhone11
使用demo编译出来的Lokie.framework闪退，使用源码测试没有问题。

**Comment by LuckinDog** [comment]
@FFFang 这个感觉像是OC 的分类方法引入问题，你在项目中加入-ObjC 再看看？

**Comment by fliggy** [comment]
这个可能和你的xcode的版本还有运行环境有关系。 建议直接引用源码
