### ISSUE TITLE
能支持父类、子类都钩同一个方法吗

### ISSUE THREAD

**Issue by captain-black** [alibaba/Lokie#2]
如题。
我有个使用场景，钩了类A的方法插入了一些处理。后来在子类AA又要钩相同方法增加更多处理。
本来用Aspects，发现Aspects限制了，他只支持在同一继承树上相同方法只能钩一次。

**Comment by 623637646** [comment]
这个库支持 https://github.com/623637646/SwiftHook

**Comment by captain-black** [comment]
> 这个库支持 https://github.com/623637646/SwiftHook

哦？不错！试用一下先。

**Comment by 4kxl** [comment]
> 如题。
> 我有个使用场景，钩了类A的方法插入了一些处理。后来在子类AA又要钩相同方法增加更多处理。
> 本来用Aspects，发现Aspects限制了，他只支持在同一继承树上相同方法只能钩一次。

Lokie 是支持重复钩的。 比如现在有两个VC.  父vc是 ViewController， 子VC是 SubViewController。
你可以对这两个VC的viewDidLoad函数下钩子。

[[SubViewController class] Lokie_hookMemberSelector:@"viewDidLoad" withBlock:^(id target){
            NSLog(@"LOKIE: SubViewController before viewDidAppear");
    } policy:LokieHookPolicyAfter];
    
    [[ViewController class] Lokie_hookMemberSelector:@"viewDidLoad" withBlock:^(id target){
            NSLog(@"LOKIE: ParantViewController before viewDidAppear");
    } policy:LokieHookPolicyAfter];
    
输出日志如下所示
2021-02-22 15:23:16.937772+0800 test_lokie[1343:3374564] LOKIE: ParantViewController before viewDidAppear
2021-02-22 15:23:20.821991+0800 test_lokie[1343:3374564] LOKIE: SubViewController before viewDidAppear
